implemented zerotier

diff --git a/zerotier/zerotier.SlackBuild b/zerotier/zerotier.SlackBuild
--- a/zerotier/zerotier.SlackBuild
+++ b/zerotier/zerotier.SlackBuild
@@ -1,32 +1,17 @@
-#!/bin/sh
+#!/bin/bash -e
 
-# Slackware build script for zerotier
+#RufusWilson revision date 2022/01/18
 
-# Copyright 2022 Rufus Wilson, Europe
-# All rights reserved.
-#
-# Redistribution and use of this script, with or without modification, is
-# permitted provided that the following conditions are met:
-#
-# 1. Redistributions of this script must retain the above copyright
-#    notice, this list of conditions and the following disclaimer.
-#
-#  THIS SOFTWARE IS PROVIDED BY THE AUTHOR "AS IS" AND ANY EXPRESS OR IMPLIED
-#  WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF
-#  MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED.  IN NO
-#  EVENT SHALL THE AUTHOR BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL,
-#  SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
-#  PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS;
-#  OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY,
-#  WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR
-#  OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF
-#  ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
+#Set initial variables:	
+CWD=$(pwd)
+if [ "$TMP" = "" ]; then
+  TMP=/tmp
+fi
 
-PRGNAM=zerotier
-VERSION=${VERSION:-1.8.4_amd64}
-BUILD=${BUILD:-1}
-TAG=${TAG:-_SBo}
+# The version which appears in the application's filename
+VERSION=${VERSION:-1.8.4}
 
+# Automatically determine the architecture we're building on:
 if [ -z "$ARCH" ]; then
   case "$( uname -m )" in
     i?86) ARCH=i486 ;;
@@ -35,38 +20,73 @@ if [ -z "$ARCH" ]; then
   esac
 fi
 
-CWD=$(pwd)
-TMP=${TMP:-/tmp/SBo}
-PKG=$TMP/package-$PRGNAM
-OUTPUT=${OUTPUT:-/tmp}
+# The application's name
+APP=zerotier
 
-set -eux
+# The installation directory of the package (where its actual directory
+# structure will be created) 
+PKG=$TMP/package-$APP
 
-rm -rf $PKG
-mkdir -p $TMP $PKG $OUTPUT
-cd $TMP
-rm -rf ${PRGNAM}-$VERSION
-tar xvf $CWD/${PRGNAM}_$VERSION.tgz
-cd ${PRGNAM}_$VERSION
-chown -R root:root .
-find -L . \
- \( -perm 777 -o -perm 775 -o -perm 750 -o -perm 711 -o -perm 555 \
-  -o -perm 511 \) -exec chmod 755 {} \; -o \
- \( -perm 666 -o -perm 664 -o -perm 640 -o -perm 600 -o -perm 444 \
-  -o -perm 440 -o -perm 400 \) -exec chmod 644 {} \;
+if [ "$ARCH" = "i486" ]; then
+  SLKCFLAGS="-O2 -march=i486 -mtune=i686"
+  LIBDIRSUFFIX=""
+elif [ "$ARCH" = "i686" ]; then
+  SLKCFLAGS="-O2 -march=i686 -mtune=i686"
+  LIBDIRSUFFIX=""
+elif [ "$ARCH" = "x86_64" ]; then
+  SLKCFLAGS="-O2 -fPIC"
+  LIBDIRSUFFIX="64"
+else
+  SLKCFLAGS="-O2"
+  LIBDIRSUFFIX=""
+fi
 
-mkdir -p $PKG/usr/doc/$PRGNAM-$VERSION
-cat $CWD/$PRGNAM.SlackBuild > $PKG/usr/doc/$PRGNAM-$VERSION/$PRGNAM.SlackBuild
+# Delete the leftover directories if they exist (due to a previous build)
+# and (re)create the packaging directory
+rm -rf $PKG 
+mkdir -p $TMP $PKG
+rm -rf $TMP/$APP-$VERSION
 
+# Change to the TMP directory
+cd $TMP || exit 1
+
+# Download the source
+wget "https://api.github.com/repos/zerotier/ZeroTierOne/tarball/${VERSION}" -O $APP-$VERSION.tar.gz
+
+# Extract the application source in TMP
+# Note: if your application comes as a tar.bz2, you need tar -jxvf
+tar -zxf $APP-$VERSION.tar.gz || exit 1
+
+# Change to the application source directory
+cd zerotier-ZeroTierOne* || exit 1
+
+# Change ownership and permissions if necessary
+# This may not be needed in some source tarballs, but it never hurts
+chmod -R u+w,go+r-w,a-s .
+
+# Compile the source, but exit if anything goes wrong
+make one || exit 1
+
+# Install everything into the package directory, but exit if anything goes wrong
+make install DESTDIR=$PKG || exit 1
+
+# Clean up
+find $PKG -type l -exec rm {} \;
+rm -rf $PKG/usr/man
+rm -rf $PKG/var
+
+# Create the ./install directory and copy the slack-desc into it
 mkdir -p $PKG/install
 cat $CWD/slack-desc > $PKG/install/slack-desc
 
-mkdir -p $PKG/usr/bin
-cp $TMP/${PRGNAM}_$VERSION/zerotier $PKG/usr/bin/zerotier
-mkdir -p $PKG/usr/sbin
-cp $TMP/${PRGNAM}_$VERSION/zerotierd $PKG/usr/sbin/zerotierd
-mkdir -p $PKG/var/run/zerotier
-mkdir -p $PKG/var/lib/zerotier
+# Strip some libraries and binaries
+( cd $PKG
+  find . | xargs file | grep "executable" | grep ELF | cut -f 1 -d : | xargs -r strip --strip-unneeded #2> /dev/null
+  find . | xargs file | grep "shared object" | grep ELF | cut -f 1 -d : | xargs -r strip --strip-unneeded #2> /dev/null
+)
 
-cd $PKG
-/sbin/makepkg -l y -c n $OUTPUT/$PRGNAM-$VERSION-$ARCH-$BUILD$TAG.${PKGTYPE:-txz}
+# Build the package
+( cd $PKG
+  /sbin/makepkg -l y -c n $CWD/$APP-$VERSION-$ARCH.txz
+)
+
